use std::str::FromStr;

#[derive(Debug, Clone, Copy)]
pub enum WindowEvent {
    AiaEnd,
    AiaStart,
    ConsoleCaret,
    ConsoleEnd,
    ConsoleEndApplication,
    ConsoleLayout,
    ConsoleStartApplication,
    ConsoleUpdateRegion,
    ConsoleUpdateScroll,
    ConsoleUpdateSimple,
    ObjectAcceleratorchange,
    ObjectCloaked,
    ObjectContentscrolled,
    ObjectCreate,
    ObjectDefactionchange,
    ObjectDescriptionchange,
    ObjectDestroy,
    ObjectDragcancel,
    ObjectDragcomplete,
    ObjectDragdropped,
    ObjectDragenter,
    ObjectDragleave,
    ObjectDragstart,
    ObjectEnd,
    ObjectFocus,
    ObjectHelpchange,
    ObjectHide,
    ObjectHostedobjectsinvalidated,
    ObjectImeChange,
    ObjectImeHide,
    ObjectImeShow,
    ObjectInvoked,
    ObjectLiveregionchanged,
    ObjectLocationchange,
    ObjectNamechange,
    ObjectParentchange,
    ObjectReorder,
    ObjectSelection,
    ObjectSelectionadd,
    ObjectSelectionremove,
    ObjectSelectionwithin,
    ObjectShow,
    ObjectStatechange,
    ObjectTexteditConversiontargetchanged,
    ObjectTextselectionchanged,
    ObjectUncloaked,
    ObjectValuechange,
    OemDefinedEnd,
    OemDefinedStart,
    SystemAlert,
    SystemArrangmentpreview,
    SystemCaptureend,
    SystemCapturestart,
    SystemContexthelpend,
    SystemContexthelpstart,
    SystemDesktopswitch,
    SystemDialogend,
    SystemDialogstart,
    SystemDragdropend,
    SystemDragdropstart,
    SystemEnd,
    SystemForeground,
    SystemImeKeyNotification,
    SystemMenuend,
    SystemMenupopupend,
    SystemMenupopupstart,
    SystemMenustart,
    SystemMinimizeend,
    SystemMinimizestart,
    SystemMovesizeend,
    SystemMovesizestart,
    SystemScrollingend,
    SystemScrollingstart,
    SystemSound,
    SystemSwitchend,
    SystemSwitcherAppdropped,
    SystemSwitcherAppgrabbed,
    SystemSwitcherAppovertarget,
    SystemSwitcherCancelled,
    SystemSwitchstart,
    UiaEventidEnd,
    UiaEventidStart,
    UiaPropidEnd,
    UiaPropidStart,
    Uknown,
}
impl FromStr for WindowEvent {
    type Err = ();

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "EVENT_AIA_END" => Ok(Self::AiaEnd),
            "EVENT_AIA_START" => Ok(Self::AiaStart),
            "EVENT_CONSOLE_CARET" => Ok(Self::ConsoleCaret),
            "EVENT_CONSOLE_END" => Ok(Self::ConsoleEnd),
            "EVENT_CONSOLE_END_APPLICATION" => Ok(Self::ConsoleEndApplication),
            "EVENT_CONSOLE_LAYOUT" => Ok(Self::ConsoleLayout),
            "EVENT_CONSOLE_START_APPLICATION" => Ok(Self::ConsoleStartApplication),
            "EVENT_CONSOLE_UPDATE_REGION" => Ok(Self::ConsoleUpdateRegion),
            "EVENT_CONSOLE_UPDATE_SCROLL" => Ok(Self::ConsoleUpdateScroll),
            "EVENT_CONSOLE_UPDATE_SIMPLE" => Ok(Self::ConsoleUpdateSimple),
            "EVENT_OBJECT_ACCELERATORCHANGE" => Ok(Self::ObjectAcceleratorchange),
            "EVENT_OBJECT_CLOAKED" => Ok(Self::ObjectCloaked),
            "EVENT_OBJECT_CONTENTSCROLLED" => Ok(Self::ObjectContentscrolled),
            "EVENT_OBJECT_CREATE" => Ok(Self::ObjectCreate),
            "EVENT_OBJECT_DEFACTIONCHANGE" => Ok(Self::ObjectDefactionchange),
            "EVENT_OBJECT_DESCRIPTIONCHANGE" => Ok(Self::ObjectDescriptionchange),
            "EVENT_OBJECT_DESTROY" => Ok(Self::ObjectDestroy),
            "EVENT_OBJECT_DRAGCANCEL" => Ok(Self::ObjectDragcancel),
            "EVENT_OBJECT_DRAGCOMPLETE" => Ok(Self::ObjectDragcomplete),
            "EVENT_OBJECT_DRAGDROPPED" => Ok(Self::ObjectDragdropped),
            "EVENT_OBJECT_DRAGENTER" => Ok(Self::ObjectDragenter),
            "EVENT_OBJECT_DRAGLEAVE" => Ok(Self::ObjectDragleave),
            "EVENT_OBJECT_DRAGSTART" => Ok(Self::ObjectDragstart),
            "EVENT_OBJECT_END" => Ok(Self::ObjectEnd),
            "EVENT_OBJECT_FOCUS" => Ok(Self::ObjectFocus),
            "EVENT_OBJECT_HELPCHANGE" => Ok(Self::ObjectHelpchange),
            "EVENT_OBJECT_HIDE" => Ok(Self::ObjectHide),
            "EVENT_OBJECT_HOSTEDOBJECTSINVALIDATED" => Ok(Self::ObjectHostedobjectsinvalidated),
            "EVENT_OBJECT_IME_CHANGE" => Ok(Self::ObjectImeChange),
            "EVENT_OBJECT_IME_HIDE" => Ok(Self::ObjectImeHide),
            "EVENT_OBJECT_IME_SHOW" => Ok(Self::ObjectImeShow),
            "EVENT_OBJECT_INVOKED" => Ok(Self::ObjectInvoked),
            "EVENT_OBJECT_LIVEREGIONCHANGED" => Ok(Self::ObjectLiveregionchanged),
            "EVENT_OBJECT_LOCATIONCHANGE" => Ok(Self::ObjectLocationchange),
            "EVENT_OBJECT_NAMECHANGE" => Ok(Self::ObjectNamechange),
            "EVENT_OBJECT_PARENTCHANGE" => Ok(Self::ObjectParentchange),
            "EVENT_OBJECT_REORDER" => Ok(Self::ObjectReorder),
            "EVENT_OBJECT_SELECTION" => Ok(Self::ObjectSelection),
            "EVENT_OBJECT_SELECTIONADD" => Ok(Self::ObjectSelectionadd),
            "EVENT_OBJECT_SELECTIONREMOVE" => Ok(Self::ObjectSelectionremove),
            "EVENT_OBJECT_SELECTIONWITHIN" => Ok(Self::ObjectSelectionwithin),
            "EVENT_OBJECT_SHOW" => Ok(Self::ObjectShow),
            "EVENT_OBJECT_STATECHANGE" => Ok(Self::ObjectStatechange),
            "EVENT_OBJECT_TEXTEDIT_CONVERSIONTARGETCHANGED" => {
                Ok(Self::ObjectTexteditConversiontargetchanged)
            }

            "EVENT_OBJECT_TEXTSELECTIONCHANGED" => Ok(Self::ObjectTextselectionchanged),
            "EVENT_OBJECT_UNCLOAKED" => Ok(Self::ObjectUncloaked),
            "EVENT_OBJECT_VALUECHANGE" => Ok(Self::ObjectValuechange),
            "EVENT_OEM_DEFINED_END" => Ok(Self::OemDefinedEnd),
            "EVENT_OEM_DEFINED_START" => Ok(Self::OemDefinedStart),
            "EVENT_SYSTEM_ALERT" => Ok(Self::SystemAlert),
            "EVENT_SYSTEM_ARRANGMENTPREVIEW" => Ok(Self::SystemArrangmentpreview),
            "EVENT_SYSTEM_CAPTUREEND" => Ok(Self::SystemCaptureend),
            "EVENT_SYSTEM_CAPTURESTART" => Ok(Self::SystemCapturestart),
            "EVENT_SYSTEM_CONTEXTHELPEND" => Ok(Self::SystemContexthelpend),
            "EVENT_SYSTEM_CONTEXTHELPSTART" => Ok(Self::SystemContexthelpstart),
            "EVENT_SYSTEM_DESKTOPSWITCH" => Ok(Self::SystemDesktopswitch),
            "EVENT_SYSTEM_DIALOGEND" => Ok(Self::SystemDialogend),
            "EVENT_SYSTEM_DIALOGSTART" => Ok(Self::SystemDialogstart),
            "EVENT_SYSTEM_DRAGDROPEND" => Ok(Self::SystemDragdropend),
            "EVENT_SYSTEM_DRAGDROPSTART" => Ok(Self::SystemDragdropstart),
            "EVENT_SYSTEM_END" => Ok(Self::SystemEnd),
            "EVENT_SYSTEM_FOREGROUND" => Ok(Self::SystemForeground),
            "EVENT_SYSTEM_IME_KEY_NOTIFICATION" => Ok(Self::SystemImeKeyNotification),
            "EVENT_SYSTEM_MENUEND" => Ok(Self::SystemMenuend),
            "EVENT_SYSTEM_MENUPOPUPEND" => Ok(Self::SystemMenupopupend),
            "EVENT_SYSTEM_MENUPOPUPSTART" => Ok(Self::SystemMenupopupstart),
            "EVENT_SYSTEM_MENUSTART" => Ok(Self::SystemMenustart),
            "EVENT_SYSTEM_MINIMIZEEND" => Ok(Self::SystemMinimizeend),
            "EVENT_SYSTEM_MINIMIZESTART" => Ok(Self::SystemMinimizestart),
            "EVENT_SYSTEM_MOVESIZEEND" => Ok(Self::SystemMovesizeend),
            "EVENT_SYSTEM_MOVESIZESTART" => Ok(Self::SystemMovesizestart),
            "EVENT_SYSTEM_SCROLLINGEND" => Ok(Self::SystemScrollingend),
            "EVENT_SYSTEM_SCROLLINGSTART" => Ok(Self::SystemScrollingstart),
            "EVENT_SYSTEM_SOUND" => Ok(Self::SystemSound),
            "EVENT_SYSTEM_SWITCHEND" => Ok(Self::SystemSwitchend),
            "EVENT_SYSTEM_SWITCHER_APPDROPPED" => Ok(Self::SystemSwitcherAppdropped),
            "EVENT_SYSTEM_SWITCHER_APPGRABBED" => Ok(Self::SystemSwitcherAppgrabbed),
            "EVENT_SYSTEM_SWITCHER_APPOVERTARGET" => Ok(Self::SystemSwitcherAppovertarget),
            "EVENT_SYSTEM_SWITCHER_CANCELLED" => Ok(Self::SystemSwitcherCancelled),
            "EVENT_SYSTEM_SWITCHSTART" => Ok(Self::SystemSwitchstart),
            "EVENT_UIA_EVENTID_END" => Ok(Self::UiaEventidEnd),
            "EVENT_UIA_EVENTID_START" => Ok(Self::UiaEventidStart),
            "EVENT_UIA_PROPID_END" => Ok(Self::UiaPropidEnd),
            "EVENT_UIA_PROPID_START" => Ok(Self::UiaPropidStart),
            _ => Ok(Self::Uknown),
        }
    }
}
pub fn parse_event<'a>(id: u32) -> &'a str {
    return match id {
        45055 => "EVENT_AIA_END",
        40960 => "EVENT_AIA_START",
        16385 => "EVENT_CONSOLE_CARET",
        16639 => "EVENT_CONSOLE_END",
        16391 => "EVENT_CONSOLE_END_APPLICATION",
        16389 => "EVENT_CONSOLE_LAYOUT",
        16390 => "EVENT_CONSOLE_START_APPLICATION",
        16386 => "EVENT_CONSOLE_UPDATE_REGION",
        16388 => "EVENT_CONSOLE_UPDATE_SCROLL",
        16387 => "EVENT_CONSOLE_UPDATE_SIMPLE",
        32786 => "EVENT_OBJECT_ACCELERATORCHANGE",
        32791 => "EVENT_OBJECT_CLOAKED",
        32789 => "EVENT_OBJECT_CONTENTSCROLLED",
        32768 => "EVENT_OBJECT_CREATE",
        32785 => "EVENT_OBJECT_DEFACTIONCHANGE",
        32781 => "EVENT_OBJECT_DESCRIPTIONCHANGE",
        32769 => "EVENT_OBJECT_DESTROY",
        32802 => "EVENT_OBJECT_DRAGCANCEL",
        32803 => "EVENT_OBJECT_DRAGCOMPLETE",
        32806 => "EVENT_OBJECT_DRAGDROPPED",
        32804 => "EVENT_OBJECT_DRAGENTER",
        32805 => "EVENT_OBJECT_DRAGLEAVE",
        32801 => "EVENT_OBJECT_DRAGSTART",
        33023 => "EVENT_OBJECT_END",
        32773 => "EVENT_OBJECT_FOCUS",
        32784 => "EVENT_OBJECT_HELPCHANGE",
        32771 => "EVENT_OBJECT_HIDE",
        32800 => "EVENT_OBJECT_HOSTEDOBJECTSINVALIDATED",
        32809 => "EVENT_OBJECT_IME_CHANGE",
        32808 => "EVENT_OBJECT_IME_HIDE",
        32807 => "EVENT_OBJECT_IME_SHOW",
        32787 => "EVENT_OBJECT_INVOKED",
        32793 => "EVENT_OBJECT_LIVEREGIONCHANGED",
        32779 => "EVENT_OBJECT_LOCATIONCHANGE",
        32780 => "EVENT_OBJECT_NAMECHANGE",
        32783 => "EVENT_OBJECT_PARENTCHANGE",
        32772 => "EVENT_OBJECT_REORDER",
        32774 => "EVENT_OBJECT_SELECTION",
        32775 => "EVENT_OBJECT_SELECTIONADD",
        32776 => "EVENT_OBJECT_SELECTIONREMOVE",
        32777 => "EVENT_OBJECT_SELECTIONWITHIN",
        32770 => "EVENT_OBJECT_SHOW",
        32778 => "EVENT_OBJECT_STATECHANGE",
        32816 => "EVENT_OBJECT_TEXTEDIT_CONVERSIONTARGETCHANGED",
        32788 => "EVENT_OBJECT_TEXTSELECTIONCHANGED",
        32792 => "EVENT_OBJECT_UNCLOAKED",
        32782 => "EVENT_OBJECT_VALUECHANGE",
        511 => "EVENT_OEM_DEFINED_END",
        257 => "EVENT_OEM_DEFINED_START",
        2 => "EVENT_SYSTEM_ALERT",
        32790 => "EVENT_SYSTEM_ARRANGMENTPREVIEW",
        9 => "EVENT_SYSTEM_CAPTUREEND",
        8 => "EVENT_SYSTEM_CAPTURESTART",
        13 => "EVENT_SYSTEM_CONTEXTHELPEND",
        12 => "EVENT_SYSTEM_CONTEXTHELPSTART",
        32 => "EVENT_SYSTEM_DESKTOPSWITCH",
        17 => "EVENT_SYSTEM_DIALOGEND",
        16 => "EVENT_SYSTEM_DIALOGSTART",
        15 => "EVENT_SYSTEM_DRAGDROPEND",
        14 => "EVENT_SYSTEM_DRAGDROPSTART",
        255 => "EVENT_SYSTEM_END",
        3 => "EVENT_SYSTEM_FOREGROUND",
        41 => "EVENT_SYSTEM_IME_KEY_NOTIFICATION",
        5 => "EVENT_SYSTEM_MENUEND",
        7 => "EVENT_SYSTEM_MENUPOPUPEND",
        6 => "EVENT_SYSTEM_MENUPOPUPSTART",
        4 => "EVENT_SYSTEM_MENUSTART",
        23 => "EVENT_SYSTEM_MINIMIZEEND",
        22 => "EVENT_SYSTEM_MINIMIZESTART",
        11 => "EVENT_SYSTEM_MOVESIZEEND",
        10 => "EVENT_SYSTEM_MOVESIZESTART",
        19 => "EVENT_SYSTEM_SCROLLINGEND",
        18 => "EVENT_SYSTEM_SCROLLINGSTART",
        1 => "EVENT_SYSTEM_SOUND",
        21 => "EVENT_SYSTEM_SWITCHEND",
        38 => "EVENT_SYSTEM_SWITCHER_APPDROPPED",
        36 => "EVENT_SYSTEM_SWITCHER_APPGRABBED",
        37 => "EVENT_SYSTEM_SWITCHER_APPOVERTARGET",
        39 => "EVENT_SYSTEM_SWITCHER_CANCELLED",
        20 => "EVENT_SYSTEM_SWITCHSTART",
        20223 => "EVENT_UIA_EVENTID_END",
        19968 => "EVENT_UIA_EVENTID_START",
        30207 => "EVENT_UIA_PROPID_END",
        29952 => "EVENT_UIA_PROPID_START",
        _ => "UNKNOWN",
    };
}
