pub mod animation;
pub mod app_border;
pub mod app_info;
pub mod app_window;
pub mod color;
pub mod config;
pub mod manager;
pub mod monitor_info;
mod overlay_handler;
pub mod statusbar;
pub mod sys;
pub mod widget;
pub mod win_api;
pub mod win_event;
pub mod workspaces;
